name: release

on:
  push:
    tags:
      - 'v*'
    branches: [master]

jobs:
  g8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout ESW repo
        uses: actions/checkout@v2
        with:
          repository: tmtsoftware/esw

      - name: Cache ~/.cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-coursier-${{ hashFiles('project/Libs.scala') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      - name: Cache ~/.sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Publish Local checked out ESW repo
        run: |
          sbtn clean
          sbtn publishLocal

      - name: create new project from csw-http-service-template.g8 template
        run: |
          g8 tmtsoftware/csw-http-service-template.g8 --name=sample

      - name: Build
        working-directory: ./sample
        run: |
          sbtn clean 
          sbtn test

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-release
